//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;

namespace WebNoteAOP.Models.WebNote
{
    [System.CodeDom.Compiler.GeneratedCode("ADO.NET Unit Testable Repository Generator", "0.5")]
    public partial class Note
    {
        #region Primitive Properties
    
        public virtual int NoteId
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string Message
        {
            get;
            set;
        }
    
        public virtual System.DateTime Added
        {
            get;
            set;
        }

        #endregion
    	
    
    	#if !DO_NOT_INCLUDE_EQUALITY_MEMBERS  
        #region Equality Members
        
        /// <summary>
        /// Implements the operator ==.
        /// </summary>
        /// <param name="left">first object to compare</param>
        /// <param name="right">second object to compare</param>
        /// <returns>The result of the operator.</returns>
        public static bool operator ==(Note left, Note right)
        {
            return Equals(left, right);
        }
    
        /// <summary>
        /// Implements the operator !=.
        /// </summary>
        /// <param name="left">first object to compare</param>
        /// <param name="right">second object to compare</param>
        /// <returns>The result of the operator.</returns>
        public static bool operator !=(Note left, Note right)
        {
            return !Equals(left, right);
        }	
    
        /// <summary>
        /// Determines whether the specified <see cref="Note"/> is equal to this instance.
        /// </summary>
        /// <param name="other">The <see cref="Note"/> to compare with this instance.</param>
        /// <returns>
        ///     <c>true</c> if the specified <see cref="Note"/> is equal to this instance; otherwise, <c>false</c>.
        /// </returns>
        public bool Equals(Note other)
        {
            if (ReferenceEquals(null, other))
            {
                return false;
            }
    
            if (ReferenceEquals(this, other))
            {
                return true;
            }
    
            if (other.NoteId != this.NoteId) 
            {
                return false;
            }
    
            if (other.Title != this.Title) 
            {
                return false;
            }
    
            if (other.Message != this.Message) 
            {
                return false;
            }
    
            if (other.Added != this.Added) 
            {
                return false;
            }
    	
            return true;
        }
        
        /// <summary>
        /// Determines whether the specified <see cref="System.Object"/> is equal to this instance.
        /// </summary>
        /// <param name="obj">The <see cref="System.Object"/> to compare with this instance.</param>
        /// <returns>
        ///     <c>true</c> if the specified <see cref="System.Object"/> is equal to this instance; otherwise, <c>false</c>.
        /// </returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }
    
            if (ReferenceEquals(this, obj))
            {
                return true;
            }
    
            if (obj.GetType() != typeof(Note))
            {
                return false;
            }
    
            return Equals((Note)obj);
        }
        
        /// <summary>
        /// Returns a hash code for this instance.
        /// </summary>
        /// <returns>
        /// A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. 
        /// </returns>
        public override int GetHashCode()
        {
    		if (this.NoteId != 0) 
    		{
            	return NoteId;
    		}
    
    		List<object> entities = new List<object>();
            entities.Add(this.NoteId);
            entities.Add(this.Title);
            entities.Add(this.Message);
            entities.Add(this.Added);
    		return CombineHashCodes(entities.ToArray());
        }
    	
        /// <summary>Computing a useful hash-code by left-shifting by 5 bits before XORing</summary>
        public static int CombineHashCodes(params object[] objects)
        {
            int hash = 0;
    
            for (int index = 0; index < objects.Length; index++)
            {
                hash = (hash << 5) + hash;
                hash ^= GetEntryHash(objects[index]);
            }
    
            return hash;
        }
    	
        private static int GetEntryHash(object entry)
        {
            int entryHash = 0x61E04917; // slurped from .Net runtime internals...
    
            if (entry != null)
            {
                object[] subObjects = entry as object[];
    
                if (subObjects != null)
                {
                    entryHash = CombineHashCodes(subObjects);
                }
                else
                {
                    entryHash = entry.GetHashCode();
                }
            }
    
            return entryHash;
        }

        #endregion
    	#endif
     
    }
}
