//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
using System.Data.Objects;

namespace WebNoteAOP.Models.WebNote
{
    /// <summary>
    /// Additional extension for interface <code>IQueryable</code>, to
    /// allow includes on <code>IObjectSet</code> when using mocking contexts.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("ADO.NET Unit Testable Repository Generator", "0.5")]
    public static class IQueryableExtension
    {
        public static IQueryable<T> Include<T>
            (this IQueryable<T> source, string path)
            where T : class
        {
            ObjectQuery<T> objectQuery = source as ObjectQuery<T>;
            if (objectQuery != null)
            {
                return objectQuery.Include(path);
            }
            return source;
        }
    }
}



