//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Objects;

namespace WebNoteAOP.Models.WebNote.WebNoteUnitTest
{
    /// <summary>
    /// The concrete mock context object that implements the context's interface.
    /// Provide an instance of this mock context class to client logic when testing, 
    /// instead of providing a functional context object.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("ADO.NET Unit Testable Repository Generator", "0.5")]
    public partial class WebNoteMock : IWebNote
    {
        public IObjectSet<Note> Notes
        {
            get { return _notes  ?? (_notes = new MockObjectSet<Note>()); }
            set { _notes  = value; }
        }
        private IObjectSet<Note> _notes;
        
        
        
         /// <summary>
        /// Will be true if SaveChanges was called
        /// </summary>	
        public bool SavesChanged { get; set; }
    
        /// <summary>
        /// Would persist all updates to the store.
        /// </summary>
        /// <returns>would return the number of saved objects, here: always '1'</returns>
        public int SaveChanges()
        {
            this.SavesChanged = true;
            return 1; // of course, this is not always the correct number, don't test for that!
        }
    }
}
