//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.EntityClient;
using System.Data.Objects;
#if !DO_NOT_USE_UNITY
using Microsoft.Practices.Unity;
#endif

namespace WebNoteAOP.Models.WebNote
{
    /// <summary>
    /// The functional concrete object context. This is just like the normal
    /// context that would be generated using the POCO artefact generator, 
    /// apart from the fact that this one implements an interface containing 
    /// the entity set properties and exposes <code>IObjectSet</code>
    /// instances for entity set properties.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("ADO.NET Unit Testable Repository Generator", "0.5")]
    public partial class WebNote : ObjectContext, IWebNote 
    {
        public const string ConnectionString = "name=WebNote";
        public const string ContainerName = "WebNote";
    
        #region Constructors
    
    	#if !DO_NOT_USE_UNITY
    	[InjectionConstructor]	
    	#endif
        public WebNote():
            base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public WebNote(string connectionString):
            base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public WebNote(EntityConnection connection):
            base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public IObjectSet<Note> Notes
        {
            get { return _notes ?? (_notes = CreateObjectSet<Note>("Notes")); }
        }
        private ObjectSet<Note> _notes;

        #endregion
    }
}
