using System.Linq;
using Raven.Client.Indexes;

namespace WebNoteTests.ExplorativeTests.RavenDb
{
    public class Logs_SearchIndex : AbstractIndexCreationTask<LogEntry, Logs_SearchIndex.Result>
    {
        public class Result
        {
            public string Country { get; set; }
            public int Size { get; set; }
            public int Count { get; set; }
        }

        // The index name generated by this is going to be Logs/SearchIndex
        public Logs_SearchIndex()
        {
            Map =  logEntries => from entry in logEntries
                                 select new Result
                                 { 
                                     Country = entry.Country,
                                     Size = entry.Size,
                                     Count = 1
                                 };

            Reduce = results => from entry in results
                                group entry by entry.Country into e
                                select new Result
                                {
                                    Country = e.Key,
                                    Count = e.Sum(x => x.Count),
                                    Size = e.Sum(x => x.Size),
                                };
        }
    }
}
